version: "3.7"

services:
  my-todo:
    image: my-todo-image
    build: .
  docs:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8000:8000
    volumes:
      - ./:/app
