name: CI/CD Pipeline
on:
  push:
    branches:
      - dev
      - staging
  pull_request:
    branches:
      - staging
      - main
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json  # 🔥 Chỉ định file lock

      - name: Install dependencies
        run: |
          cd backend  # 🔥 Di chuyển vào thư mục backend
          npm ci
      - name: Build
        run: |
          cd backend 
          npm run build --if-present
      - name: Run tests
        run: |
          cd backend 
          npm test
  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image with cache
        run: docker build --cache-from=type=registry,ref=${{ secrets.DOCKER_USERNAME }}/my-todo-app:tagname -t my-todo-app ./backend
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-todo-app:tagname
      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name my-todo-container ${{ secrets.DOCKER_USERNAME }}/my-todo-app:tagname
      - name: Deploy to staging
        if: github.ref == 'refs/heads/staging'
        run: echo "Deploying to staging..."
      - name: Deploy to production
        if: github.ref == 'refs/heads/main' && github.event_name == 'pull_request'
        run: echo "Deploying to production..."
      - name: Set permissions
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "main" || "${{ github.event.pull_request.base.ref }}" == "staging" ]]; then
            ALLOWED_USERS=("devops-user" "tranvankhoa1998")
            if [[ ! " ${ALLOWED_USERS[@]} " =~ " ${{ github.actor }} " ]]; then
              echo "❌ User ${{ github.actor }} is not allowed to merge to this branch."
              exit 1
            fi
          fi
